### ISSUE TITLE
small mini menu

### ISSUE THREAD

**Issue by jeffalo** [JeffaloBob/kahoot-gui#18]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
a button or keyboard shortcut that opens a new miny menu, as per this bad mockup i made. 
![mockup](https://user-images.githubusercontent.com/40470736/74045199-a0e8f880-49cc-11ea-9007-fd86f73f1acb.png)

As seen, there is a small circle when hovered over opens up a little pill menu that shows connected bots and newest bot.

i don't know how well this can be done in electron though

**Comment by Odisseuss** [comment]
@JeffaloBob I'm gonna try to take on this issue. I'm thinking about using the notification system of electron to make a persistent notification that will act as the small menu.

**Comment by Odisseuss** [comment]
@JeffaloBob It seems the notification approach is not really working. So i thought about using another browserWindow that is frameless and transparent but it seems that on linux it doesn't work as it's supposed to, and this is a known issue with electron on linux.

I can suggest what you can do, but you must try it yourself as i don't have a windows machine.
```
app.on("ready", () => {
  const overlay = new BrowserWindow({
    frame: false,
    transparent: true,
    width: 250,
    height: 100
  });
  // Create shortcuts for stealth mode on app ready
  const hideWindowShortcut = globalShortcut.register(
    "CommandOrControl+Shift+P",
    () => {
      win.hide();
      overlay.show();
    }
  );
  const showWindowShortcut = globalShortcut.register(
    "CommandOrControl+P",
    () => {
      win.show();
      overlay.hide();
    }
  );
  createWindow();
});
```
From there you should create another html page for the new window (the mini menu) and styling it appropriately with a css file. You can try to make a div in that page and give it some border radius to make it more 'pill' shaped, and give it an rgba color to make it semi-transparent.
Also you need to find a way to get the data (bot count, bot last name used) from the yeeter.js file.

I am sorry i can't solve this issue but i hope that i gave you a general idea about what you have to do in order to solve it yourself.

**Comment by jeffalo** [comment]
@Odisseuss I see where it's supposed to go. Thanks anyways!!

**Comment by jeffalo** [comment]
I don't think this menu is really very useful, maybe this can be come to back to when crossplatform on electron is better here
