### ISSUE TITLE
stealth mode

### ISSUE THREAD

**Issue by jeffalo** [JeffaloBob/kahoot-gui#6]
**Is your feature request related to a problem? Please describe.**
host walks past your screen sees kahoot hack - no go

**Describe the solution you'd like**
stealth mode where you can quickly switch between the kahoot hack and a real kahoot instance (through embed or something)

**Describe alternatives you've considered**
alt+tab but still shows up in taskbar

**Additional context**

**Comment by Odisseuss** [comment]
@JeffaloBob I will try to solve this issue tomorrow. I think i might have found something

![kahoot-hide](https://user-images.githubusercontent.com/44244648/73491851-67e6cd80-43a7-11ea-8a8e-032882fdd89e.gif)

I can use the window.hide() electron function to completely hide the window without actually closing it. However i think the best solution is to make this a keyboard shortcut or something. Also it should have another shortcut for bringing the window back. I will look through the electron docs to see if i can find something that will be of use for this issue. Please give me some more details about how you imagine this functionality, and your thoughts on the keyboard shortcuts idea.

**Comment by Odisseuss** [comment]
@JeffaloBob 
I have implemented some shortcuts for entering/getting out of "stealth mode". I am currently working on linux and I don't have a windows/mac machine in order to test how the app reacts on those OS.

On my OS it seems like it's disappearing from the dock which means it is hidden. On windows it will probably be in the task tray, but not in the taskbar which is ok as it is not visible to someone passing by.
![kahoot-hide-shortcuts](https://user-images.githubusercontent.com/44244648/73531949-7bc81900-4413-11ea-9e02-7e7c8a10fbf0.gif)


If you own a different machine please clone the forked repo from my profile and pull the "feature-stealth-mode" branch and test it to see how the app behaves.

The shortcuts i set up are: Ctrl+Shift+P for hiding and Ctrl+P for showing.

**Comment by jeffalo** [comment]
This works perfectly. On Windows (currently my only testing machine), it disappears from the taskbar and it's not even in the task tray.

I'll find someone on MacOS to test. Thank you!!

Make a pull request, this is awesome.

**Comment by Odisseuss** [comment]
@JeffaloBob 
Sure, no problem, will do.

**Comment by jeffalo** [comment]
@Odisseuss Should I close this, as it's added and finished?

**Comment by Odisseuss** [comment]
@JeffaloBob Sure
